package com.fhi.client.vo;

import java.util.Date;

/**
 * WmsLocationRegion generated by MyEclipse Persistence Tools
 */

public class FhiClientUser implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private String id;

	private String userId;	
	
	private String passWord;
	
	private String clientName;
	
	private String rightsUrl;
	
	private String rightsType;
	
	private String rights;
		
	private String flag;
	
	private Date loginDate;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPassWord() {
		return passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	public String getClientName() {
		return clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getRightsUrl() {
		return rightsUrl;
	}

	public void setRightsUrl(String rightsUrl) {
		this.rightsUrl = rightsUrl;
	}

	public String getRightsType() {
		return rightsType;
	}

	public void setRightsType(String rightsType) {
		this.rightsType = rightsType;
	}

	public String getRights() {
		return rights;
	}

	public void setRights(String rights) {
		this.rights = rights;
	}

	public String getFlag() {
		return flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Date getLoginDate() {
		return loginDate;
	}

	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}	
}