package com.fhi.employee.vo;

import java.util.Date;

/**
 * FhiOaEmployeeEducation generated by MyEclipse Persistence Tools
 */

public class FhiOaEmployeeEducation implements java.io.Serializable {

	// Fields

	private String id;

	private Date startDate;

	private Date endDate;

	private String employeeId;

	private String university;

	private String provePerson;

	private String phone;

	private String profession;

	private String comment;

	private String degree;

	private String creator;

	private Date addDate;

	// Constructors

	/** default constructor */
	public FhiOaEmployeeEducation() {
	}

	/** full constructor */
	public FhiOaEmployeeEducation(Date startDate, Date endDate,
			String employeeId, String university, String provePerson,
			String phone, String profession, String comment, String degree,
			String creator, Date addDate) {
		this.startDate = startDate;
		this.endDate = endDate;
		this.employeeId = employeeId;
		this.university = university;
		this.provePerson = provePerson;
		this.phone = phone;
		this.profession = profession;
		this.comment = comment;
		this.degree = degree;
		this.creator = creator;
		this.addDate = addDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getUniversity() {
		return this.university;
	}

	public void setUniversity(String university) {
		this.university = university;
	}

	public String getProvePerson() {
		return this.provePerson;
	}

	public void setProvePerson(String provePerson) {
		this.provePerson = provePerson;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

}