package com.fhi.information.picture.vo;

import java.util.Date;


/**
 * WmsAutoCode generated by MyEclipse Persistence Tools
 */

public class FhiPicture {

     private String id;
     //文档分类
     private String classId;
     //分类名称
     private String className;
     //文档编号
     private String code;
     //标题
     private String title;
     //内容
     private String content;
     //文件集
     private String files;
     //可见角色
     private String visible;
     //封面文件链接
     private String cover;
     //发布人ID
     private String creater;
     //发布人 姓名
     private String creatorName;
     //发布时间
     private Date createDate;
     //是否为自动编号
     private boolean autoCode;

	public FhiPicture(){
		this.createDate = new Date();
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		if(title!=null){
			title = title.trim();
		}
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getFiles() {
		return files;
	}

	public void setFiles(String files) {
		this.files = files;
	}

	public String getCreater() {
		return creater;
	}

	public void setCreater(String creater) {
		this.creater = creater;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getVisible() {
		return visible;
	}

	public void setVisible(String visible) {
		this.visible = visible;
	}

	public boolean isAutoCode() {
		return autoCode;
	}

	public void setAutoCode(boolean autoCode) {
		this.autoCode = autoCode;
	}

	public String getClassId() {
		return classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getCover() {
		return cover;
	}

	public void setCover(String cover) {
		this.cover = cover;
	}

	public String getCreatorName() {
		return creatorName;
	}

	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}	
}