package com.fhi.accept.vo;

import java.util.Date;

/**
 * FhiOaRetmoney generated by MyEclipse Persistence Tools
 */

public class FhiOaRetmoney implements java.io.Serializable {

	// Fields

	private String id;

	private String moneyItem;

	private Float retCount;

	private Date retDate;

	private String comment;

	private Date createDate;

	private String creator;

	private String acceptOrderId;

	// Constructors

	/** default constructor */
	public FhiOaRetmoney() {
	}

	/** minimal constructor */
	public FhiOaRetmoney(String id) {
		this.id = id;
	}

	/** full constructor */
	public FhiOaRetmoney(String id, String moneyItem, Float retCount,
			Date retDate, String comment, Date createDate, String creator,
			String acceptOrderId) {
		this.id = id;
		this.moneyItem = moneyItem;
		this.retCount = retCount;
		this.retDate = retDate;
		this.comment = comment;
		this.createDate = createDate;
		this.creator = creator;
		this.acceptOrderId = acceptOrderId;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getMoneyItem() {
		return this.moneyItem;
	}

	public void setMoneyItem(String moneyItem) {
		this.moneyItem = moneyItem;
	}

	public Float getRetCount() {
		return this.retCount;
	}

	public void setRetCount(Float retCount) {
		this.retCount = retCount;
	}

	public Date getRetDate() {
		return this.retDate;
	}

	public void setRetDate(Date retDate) {
		this.retDate = retDate;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public String getAcceptOrderId() {
		return this.acceptOrderId;
	}

	public void setAcceptOrderId(String acceptOrderId) {
		this.acceptOrderId = acceptOrderId;
	}

}