package com.fhi.employee.vo;

import java.util.Date;

import com.fhi.framework.utils.date.DataUtils;

/**
 * FhiOaEmployeeFamily generated by MyEclipse Persistence Tools
 */

public class FhiOaEmployeeFamily implements java.io.Serializable {

	// Fields

	private String id;

	private String employeeId;

	private String name;

	private Integer age;
	
	private Date birthday ;

	private String birthdayStr ;  //时间注入

	private String workCompany;

	private String phone;

	private String relationship;

	private String creator;

	private Date addDate;

	// Constructors

	/** default constructor */
	public FhiOaEmployeeFamily() {
	}

	/** full constructor */
	public FhiOaEmployeeFamily(String employeeId, String name, Integer age,
			String workCompany, String phone, String relationship,
			String creator, Date addDate) {
		this.employeeId = employeeId;
		this.name = name;
		this.age = age;
		this.workCompany = workCompany;
		this.phone = phone;
		this.relationship = relationship;
		this.creator = creator;
		this.addDate = addDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getWorkCompany() {
		return this.workCompany;
	}

	public void setWorkCompany(String workCompany) {
		this.workCompany = workCompany;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	} 
	public void setBirthdayStr(String birthdayStr) {
		this.birthday = DataUtils.getDateByString(birthdayStr);
	}

}