package com.fhi.employee.vo;

import java.util.Date;

/**
 * FhiOaEmployeeWork generated by MyEclipse Persistence Tools
 */

public class FhiOaEmployeeWork implements java.io.Serializable {

	// Fields

	private String id;

	private Date startDate;

	private Date endDate;

	private String employeeId;

	private String company;

	private String phone;

	private String provePerson;

	private String job;

	private String creator;

	private Date addDate;

	private String comment;

	// Constructors

	/** default constructor */
	public FhiOaEmployeeWork() {
	}

	/** full constructor */
	public FhiOaEmployeeWork(Date startDate, Date endDate, String employeeId,
			String company, String phone, String provePerson, String job,
			String creator, Date addDate, String comment) {
		this.startDate = startDate;
		this.endDate = endDate;
		this.employeeId = employeeId;
		this.company = company;
		this.phone = phone;
		this.provePerson = provePerson;
		this.job = job;
		this.creator = creator;
		this.addDate = addDate;
		this.comment = comment;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getProvePerson() {
		return this.provePerson;
	}

	public void setProvePerson(String provePerson) {
		this.provePerson = provePerson;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}