package com.fhi.system.sysmsg.vo;

import java.util.Date;


/**
 * WmsAutoCode generated by MyEclipse Persistence Tools
 */

public class SysMsg  implements java.io.Serializable {

     private String id;
     //通知用户
     private String userId;
     //是否读取0未读 1已读
     private Integer isRead;
     //创建时间
     private Date createDate;
     //类型 0工作计划1系统通知
     private Integer sysType;
     //种类
     private Integer sysClass;
     //种类名称
     private String sysClassName;
     //标题
     private String title;
     //内容
     private String content;
     //连接
     private String url;
     
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}
	public Integer getIsRead() {		
		return isRead==null?0:isRead;
	}
	public void setIsRead(Integer read) {
		this.isRead = read;
	}
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getSysType() {
		return sysType;
	}
	public void setSysType(Integer sysType) {
		this.sysType = sysType;
	}
	public Integer getSysClass() {
		return sysClass;
	}
	public void setSysClass(Integer sysClass) {
		this.sysClass = sysClass;
	}
	public String getSysClassName() {
		return sysClassName;
	}
	public void setSysClassName(String sysClassName) {
		this.sysClassName = sysClassName;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	
	public Integer getGrade(){
		return this.getSysClass()%2;
	}
}