package com.fhi.system.sysmsg.vo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.fhi.framework.utils.date.DataUtils;


/**
 * WmsAutoCode generated by MyEclipse Persistence Tools
 */

public class SysMsgSetup  implements java.io.Serializable {

     private String id;
     //创建用户
     private String userId;
     //关联项
     private String linked;
     //创建时间
     private Date createDate;
     //开始时间
     private Date startDate;
     //截止日期
     private Date deadlineDate;
     //额外通知人员 以;分开
     private String userIds;
     //额外通知人员 以;分开
     private String userNames;
     //类型 0工作计划1系统通知
     private Integer sysType;
     //种类
     private Integer sysClass;
     //种类名称
     private String sysClassName;
     //标题
     private String title;
     //内容
     private String content;
     //连接
     private String url;
     
     /**
      * 根据发送用户<br>
      * 返回当前需要发送的所有通知信息<br>
      * 包含创建者自己<br>
      * @return  List
      */
     public List<SysMsg> getSysMsgs(){
 		List<SysMsg> list = new ArrayList();
 		list.add(this.getSysMsg(this.getUserId()));
 		if(this.userIds!=null&&!"".equals(this.userIds)){
 			String[] userIds = this.userIds.split(";");
 			for(int i=0;i<userIds.length;i++){
 				list.add(this.getSysMsg(userIds[i]));
 			}
 		}
 		return list;
 	}
     /**
      * 返回当前配置文件的信息实体
      * @param userId
      * @return
      */
     public SysMsg getSysMsg(String userId){
    	 SysMsg sysMsg=new SysMsg();
    	 sysMsg.setUserId(userId);
    	 sysMsg.setCreateDate(new Date());
    	 sysMsg.setSysType(this.getSysType());
    	 sysMsg.setSysClass(this.getSysClass());
    	 sysMsg.setSysClassName(this.getSysClassName());
    	 
    	 sysMsg.setTitle(this.getTitle());    	
    	 sysMsg.setContent(this.getContent());
    	 sysMsg.setUrl(this.getUrl());
    	 
    	 return sysMsg;
     }
     
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}
	public Date getCreateDate() {
		return createDate==null?new Date():createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public Date getStartDate() {
		return startDate;
	}
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	public void setStartDateStr(String dateStr) {
		this.startDate = DataUtils.getDateByString(dateStr);
	}
	public Date getDeadlineDate() {
		if(deadlineDate==null){
			String t = DataUtils.format(new Date(startDate.getTime()+1000*60*60*24), "yyyy-MM-dd");
			deadlineDate =DataUtils.getDateByString(t);
		}
		return deadlineDate;
	}
	public void setDeadlineDate(Date deadlineDate) {
		this.deadlineDate = deadlineDate;
	}
	public String getUserIds() {
		return userIds;
	}
	public void setUserIds(String userIds) {
		this.userIds = userIds;
	}
	public Integer getSysType() {
		return sysType;
	}
	public void setSysType(Integer sysType) {
		this.sysType = sysType;
	}
	public Integer getSysClass() {
		return sysClass;
	}
	public void setSysClass(Integer sysClass) {
		this.sysClass = sysClass;
	}
	public String getSysClassName() {
		return sysClassName;
	}
	public void setSysClassName(String sysClassName) {
		this.sysClassName = sysClassName;
	}
	public String getTitle() {
		if(title!=null){
			title = title.trim();
		}
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getLinked() {
		return linked;
	}
	public void setLinked(String linked) {
		this.linked = linked;
	}
	public String getUserNames() {
		return userNames;
	}
	public void setUserNames(String userNames) {
		this.userNames = userNames;
	}	
}