package com.fhi.department.vo;

import java.util.Date;

/**
 * FhiOaDepartment generated by MyEclipse Persistence Tools
 */

public class FhiOaDepartment implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String id;

	private String depCode;

	private String depName;

	private String comId;

	private String comName;

	private String parentDepId;

	private String parentDepName;

	private String leader;

	private String description;

	private String valid;

	private String creator;

	private Date addDate;

	private String address;

	private String contract;

	private Date contractTime;

	private String contractTerm;

	// Constructors

	/** default constructor */
	public FhiOaDepartment() {
	}

	/** minimal constructor */
	public FhiOaDepartment(String id) {
		this.id = id;
	}

	/** full constructor */
	public FhiOaDepartment(String id, String depCode, String depName,
			String comId, String comName, String parentDepId,
			String parentDepName, String leader, String description,
			String valid, String creator, Date addDate, String address,
			String contract, Date contractTime, String contractTerm) {
		this.id = id;
		this.depCode = depCode;
		this.depName = depName;
		this.comId = comId;
		this.comName = comName;
		this.parentDepId = parentDepId;
		this.parentDepName = parentDepName;
		this.leader = leader;
		this.description = description;
		this.valid = valid;
		this.creator = creator;
		this.addDate = addDate;
		this.address = address;
		this.contract = contract;
		this.contractTime = contractTime;
		this.contractTerm = contractTerm;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getDepCode() {
		return this.depCode;
	}

	public void setDepCode(String depCode) {
		this.depCode = depCode;
	}

	public String getDepName() {
		return this.depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

	public String getComId() {
		return this.comId;
	}

	public void setComId(String comId) {
		this.comId = comId;
	}

	public String getComName() {
		return this.comName;
	}

	public void setComName(String comName) {
		this.comName = comName;
	}

	public String getParentDepId() {
		return this.parentDepId;
	}

	public void setParentDepId(String parentDepId) {
		this.parentDepId = parentDepId;
	}

	public String getParentDepName() {
		return this.parentDepName;
	}

	public void setParentDepName(String parentDepName) {
		this.parentDepName = parentDepName;
	}

	public String getLeader() {
		return this.leader;
	}

	public void setLeader(String leader) {
		this.leader = leader;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getValid() {
		return this.valid;
	}

	public void setValid(String valid) {
		this.valid = valid;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContract() {
		return this.contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	public Date getContractTime() {
		return this.contractTime;
	}

	public void setContractTime(Date contractTime) {
		this.contractTime = contractTime;
	}

	public String getContractTerm() {
		return this.contractTerm;
	}

	public void setContractTerm(String contractTerm) {
		this.contractTerm = contractTerm;
	}

}