package com.fhi.system.vo;

/**
 * WmsConfig generated by MyEclipse Persistence Tools
 */

public class SysConfig implements java.io.Serializable {

	// Fields

	private String id;

	private Integer rowsPerpage;

	private Integer sessionInactiveInterval;
	

	
	/**
	 * 系统默认配置
	 */
	public SysConfig() {
		this.rowsPerpage = 15;	//每页15条
		this.sessionInactiveInterval = 3600;	//登陆超时30分钟
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	/**
	 * 每页显示条数
	 * 
	 * @return
	 */
	public Integer getRowsPerpage() {
		return rowsPerpage;
	}

	public void setRowsPerpage(Integer rowsPerpage) {
		this.rowsPerpage = rowsPerpage;
	}

	/**
	 * session过期时间(秒)
	 * 
	 * @return Integer
	 */
	public Integer getSessionInactiveInterval() {
		return sessionInactiveInterval;
	}

	/**
	 * session过期时间(秒)
	 * 
	 * @param sessionInactiveInterval
	 */
	public void setSessionInactiveInterval(Integer sessionInactiveInterval) {
		this.sessionInactiveInterval = sessionInactiveInterval;
	}
}