package com.fhi.utils.portmanage.vo;

import java.util.Date;


/**
 * WmsAutoCode generated by MyEclipse Persistence Tools
 */

public class FhiOsUtilsPort {

     private String id;
     //港口编号
     private String portCode;
     //港口名称
     private String portName;
     //创建人
     private String creator;
     //发布时间
     private Date createDate;
     //修改人ID
     private String mender;
     //修改时间
     private Date editDate;
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getPortCode() {
		return portCode;
	}
	public void setPortCode(String portCode) {
		this.portCode = portCode;
	}
	public String getPortName() {
		return portName;
	}
	public void setPortName(String portName) {
		this.portName = portName;
	}
	public String getCreator() {
		return creator;
	}
	public void setCreator(String creator) {
		this.creator = creator;
	}
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public String getMender() {
		return mender;
	}
	public void setMender(String mender) {
		this.mender = mender;
	}
	public Date getEditDate() {
		return editDate;
	}
	public void setEditDate(Date editDate) {
		this.editDate = editDate;
	}
}