package com.fhi.journal.vo;

import java.io.UnsupportedEncodingException;
import java.util.Date;


/**
 * WmsAutoCode generated by MyEclipse Persistence Tools
 */

public class FhiJournalVote  implements java.io.Serializable {

	private String id;
	//Customer Code
	private String code;
	
	//好评
	private Integer good;
	//中评
	private Integer ordinary;
	//差评
	private Integer noGood;
	
	//发布人Id
    private String creater;
    //发布人 姓名
    private String creatorName;
    //发布时间
    private Date createDate;
    
    public FhiJournalVote(){
    	
    }    
	public FhiJournalVote(Integer good, Integer ordinary, Integer noGood) {
		this.good = good;
		this.ordinary = ordinary;
		this.noGood = noGood;
	}
	
	public boolean inspection(){
		
		int good = this.good==null?0:this.good.intValue();
		int ordinary = this.ordinary==null?0:this.ordinary.intValue();
		int noGood = this.noGood==null?0:this.noGood.intValue();
		if(good+ordinary+noGood==1){
			return true;
		}		
		return false;
	}
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public void setCodeStr(String code) {
		try {
			this.code = new String(code.trim().getBytes("ISO-8859-1"), "UTF-8");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
	}
	public String getCreater() {
		return creater;
	}
	public void setCreater(String creater) {
		this.creater = creater;
	}
	public String getCreatorName() {
		return creatorName;
	}
	public void setCreatorName(String creatorName) {
		this.creatorName = creatorName;
	}
	public Date getCreateDate() {
		return createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	public Integer getGood() {
		return good==null?0:good;
	}
	public void setGood(Integer good) {
		this.good = good;
	}
	public Integer getOrdinary() {
		return ordinary==null?0:ordinary;
	}
	public void setOrdinary(Integer ordinary) {
		this.ordinary = ordinary;
	}
	public Integer getNoGood() {
		return noGood==null?0:noGood;
	}
	public void setNoGood(Integer noGood) {
		this.noGood = noGood;
	}	
}