package com.fhi.employee.vo;

import java.util.Date;

/**
 * FhiOaEmployeeBasic generated by MyEclipse Persistence Tools
 */

public class FhiOaEmployeeBasic implements java.io.Serializable {

	// Fields

	private String id;

	private String employeeCode;

	private String name;

	private String headPic;

	private String sex;

	private Date birthday;

	private String nomen;

	private String idcard;

	private Date inWorkDate;

	private String politics;

	private String degree;

	private Date realWorkDate;

	private String contractLength;

	private Date endDate;

	private String livePlace;

	private String livePhone;

	private String identityPlace;

	private String identityPhone;

	private String emergencyPerson;

	private String relation;

	private String emergencyPhone;

	private String companyId;

	private String companyName;

	private String depId;

	private String depName;

	private String enName;

	private String marry;

	private String job;

	private String jobLevel;

	private String mobile;

	private String phone;

	private String fax;

	private String email;

	private String msn;

	private String qq;

	private String language;

	private String langLevel;

	private Date offWorkDate;

	private String university;

	private String employeeState;

	private String salary;

	private String accountNo;

	private String bank;

	private String insureCard;

	private String creator;

	private Date addDate;

	private String postCode;

	private String nativePlace;

	private String driver;

	private String busGroup;

	private String driverCard;

	private String driveLevel;

	private String dcvalidTime;

	private Date nextCheck;

	private Date startWrokDate;

	private String account;

	private String idcardPic;

	private String accountPic;

	private String degreePic;

	private String drivePic;

	private String graduatePic;

	private String gatewayPic;

	private String checkPic;

	// Constructors

	/** default constructor */
	public FhiOaEmployeeBasic() {
	}

	/** minimal constructor */
	public FhiOaEmployeeBasic(String id) {
		this.id = id;
	}

	/** full constructor */
	public FhiOaEmployeeBasic(String id, String employeeCode, String name,
			String headPic, String sex, Date birthday, String nomen,
			String idcard, Date inWorkDate, String politics, String degree,
			Date realWorkDate, String contractLength, Date endDate,
			String livePlace, String livePhone, String identityPlace,
			String identityPhone, String emergencyPerson, String relation,
			String emergencyPhone, String companyId, String companyName,
			String depId, String depName, String enName, String marry,
			String job, String jobLevel, String mobile, String phone,
			String fax, String email, String msn, String qq, String language,
			String langLevel, Date offWorkDate, String university,
			String employeeState, String salary, String accountNo, String bank,
			String insureCard, String creator, Date addDate, String postCode,
			String nativePlace, String driver, String busGroup,
			String driverCard, String driveLevel, String dcvalidTime,
			Date nextCheck, Date startWrokDate, String account,
			String idcardPic, String accountPic, String degreePic,
			String drivePic, String graduatePic, String gatewayPic,
			String checkPic) {
		this.id = id;
		this.employeeCode = employeeCode;
		this.name = name;
		this.headPic = headPic;
		this.sex = sex;
		this.birthday = birthday;
		this.nomen = nomen;
		this.idcard = idcard;
		this.inWorkDate = inWorkDate;
		this.politics = politics;
		this.degree = degree;
		this.realWorkDate = realWorkDate;
		this.contractLength = contractLength;
		this.endDate = endDate;
		this.livePlace = livePlace;
		this.livePhone = livePhone;
		this.identityPlace = identityPlace;
		this.identityPhone = identityPhone;
		this.emergencyPerson = emergencyPerson;
		this.relation = relation;
		this.emergencyPhone = emergencyPhone;
		this.companyId = companyId;
		this.companyName = companyName;
		this.depId = depId;
		this.depName = depName;
		this.enName = enName;
		this.marry = marry;
		this.job = job;
		this.jobLevel = jobLevel;
		this.mobile = mobile;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.msn = msn;
		this.qq = qq;
		this.language = language;
		this.langLevel = langLevel;
		this.offWorkDate = offWorkDate;
		this.university = university;
		this.employeeState = employeeState;
		this.salary = salary;
		this.accountNo = accountNo;
		this.bank = bank;
		this.insureCard = insureCard;
		this.creator = creator;
		this.addDate = addDate;
		this.postCode = postCode;
		this.nativePlace = nativePlace;
		this.driver = driver;
		this.busGroup = busGroup;
		this.driverCard = driverCard;
		this.driveLevel = driveLevel;
		this.dcvalidTime = dcvalidTime;
		this.nextCheck = nextCheck;
		this.startWrokDate = startWrokDate;
		this.account = account;
		this.idcardPic = idcardPic;
		this.accountPic = accountPic;
		this.degreePic = degreePic;
		this.drivePic = drivePic;
		this.graduatePic = graduatePic;
		this.gatewayPic = gatewayPic;
		this.checkPic = checkPic;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEmployeeCode() {
		return this.employeeCode;
	}

	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getHeadPic() {
		return this.headPic;
	}

	public void setHeadPic(String headPic) {
		this.headPic = headPic;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getNomen() {
		return this.nomen;
	}

	public void setNomen(String nomen) {
		this.nomen = nomen;
	}

	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	public Date getInWorkDate() {
		return this.inWorkDate;
	}

	public void setInWorkDate(Date inWorkDate) {
		this.inWorkDate = inWorkDate;
	}

	public String getPolitics() {
		return this.politics;
	}

	public void setPolitics(String politics) {
		this.politics = politics;
	}

	public String getDegree() {
		return this.degree;
	}

	public void setDegree(String degree) {
		this.degree = degree;
	}

	public Date getRealWorkDate() {
		return this.realWorkDate;
	}

	public void setRealWorkDate(Date realWorkDate) {
		this.realWorkDate = realWorkDate;
	}

	public String getContractLength() {
		return this.contractLength;
	}

	public void setContractLength(String contractLength) {
		this.contractLength = contractLength;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getLivePlace() {
		return this.livePlace;
	}

	public void setLivePlace(String livePlace) {
		this.livePlace = livePlace;
	}

	public String getLivePhone() {
		return this.livePhone;
	}

	public void setLivePhone(String livePhone) {
		this.livePhone = livePhone;
	}

	public String getIdentityPlace() {
		return this.identityPlace;
	}

	public void setIdentityPlace(String identityPlace) {
		this.identityPlace = identityPlace;
	}

	public String getIdentityPhone() {
		return this.identityPhone;
	}

	public void setIdentityPhone(String identityPhone) {
		this.identityPhone = (identityPhone!=null?identityPhone.trim():"");
	}

	public String getEmergencyPerson() {
		return this.emergencyPerson;
	}

	public void setEmergencyPerson(String emergencyPerson) {
		this.emergencyPerson = emergencyPerson;
	}

	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

	public String getEmergencyPhone() {
		return this.emergencyPhone;
	}

	public void setEmergencyPhone(String emergencyPhone) {
		this.emergencyPhone = emergencyPhone;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getDepId() {
		return this.depId;
	}

	public void setDepId(String depId) {
		this.depId = depId;
	}

	public String getDepName() {
		return this.depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

	public String getEnName() {
		return this.enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

	public String getMarry() {
		return this.marry;
	}

	public void setMarry(String marry) {
		this.marry = marry;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getJobLevel() {
		return this.jobLevel;
	}

	public void setJobLevel(String jobLevel) {
		this.jobLevel = jobLevel;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMsn() {
		return this.msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getLangLevel() {
		return this.langLevel;
	}

	public void setLangLevel(String langLevel) {
		this.langLevel = langLevel;
	}

	public Date getOffWorkDate() {
		return this.offWorkDate;
	}

	public void setOffWorkDate(Date offWorkDate) {
		this.offWorkDate = offWorkDate;
	}

	public String getUniversity() {
		return this.university;
	}

	public void setUniversity(String university) {
		this.university = university;
	}

	public String getEmployeeState() {
		return this.employeeState;
	}

	public void setEmployeeState(String employeeState) {
		this.employeeState = employeeState;
	}

	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getInsureCard() {
		return this.insureCard;
	}

	public void setInsureCard(String insureCard) {
		this.insureCard = insureCard;
	}

	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	public String getNativePlace() {
		return this.nativePlace;
	}

	public void setNativePlace(String nativePlace) {
		this.nativePlace = nativePlace;
	}

	public String getDriver() {
		return this.driver;
	}

	public void setDriver(String driver) {
		this.driver = driver;
	}

	public String getBusGroup() {
		return this.busGroup;
	}

	public void setBusGroup(String busGroup) {
		this.busGroup = busGroup;
	}

	public String getDriverCard() {
		return this.driverCard;
	}

	public void setDriverCard(String driverCard) {
		this.driverCard = driverCard;
	}

	public String getDriveLevel() {
		return this.driveLevel;
	}

	public void setDriveLevel(String driveLevel) {
		this.driveLevel = driveLevel;
	}

	public String getDcvalidTime() {
		return this.dcvalidTime;
	}

	public void setDcvalidTime(String dcvalidTime) {
		this.dcvalidTime = dcvalidTime;
	}

	public Date getNextCheck() {
		return this.nextCheck;
	}

	public void setNextCheck(Date nextCheck) {
		this.nextCheck = nextCheck;
	}

	public Date getStartWrokDate() {
		return this.startWrokDate;
	}

	public void setStartWrokDate(Date startWrokDate) {
		this.startWrokDate = startWrokDate;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getIdcardPic() {
		return this.idcardPic;
	}

	public void setIdcardPic(String idcardPic) {
		this.idcardPic = idcardPic;
	}

	public String getAccountPic() {
		return this.accountPic;
	}

	public void setAccountPic(String accountPic) {
		this.accountPic = accountPic;
	}

	public String getDegreePic() {
		return this.degreePic;
	}

	public void setDegreePic(String degreePic) {
		this.degreePic = degreePic;
	}

	public String getDrivePic() {
		return this.drivePic;
	}

	public void setDrivePic(String drivePic) {
		this.drivePic = drivePic;
	}

	public String getGraduatePic() {
		return this.graduatePic;
	}

	public void setGraduatePic(String graduatePic) {
		this.graduatePic = graduatePic;
	}

	public String getGatewayPic() {
		return this.gatewayPic;
	}

	public void setGatewayPic(String gatewayPic) {
		this.gatewayPic = gatewayPic;
	}

	public String getCheckPic() {
		return this.checkPic;
	}

	public void setCheckPic(String checkPic) {
		this.checkPic = checkPic;
	}

}