package com.fhi.framework.upload.vo;

import java.util.Date;

/**
 * WmsAutoCode generated by MyEclipse Persistence Tools
 */

public class FhiFile implements java.io.Serializable {

	// 文件Id
	private String fileId;
	// 文件名称
	private String fileName;
	// 文件扩展名
	private String fileExt;
	// 文件类型
	private String fileType;
	// 下载次数
	private Integer downloadCount;
	// 上传用户名
	private String creator;
	// 上传时间
	private Date createDate;
	// 是否删除0 不删除 -1删除
	private Integer isDel;
	//是否是临时文件 0不是 1是
	private Integer isTemp;

	public FhiFile(String fileId) {
		this.fileId = fileId;
	}

	public FhiFile() {
	}

	/**
	 * 
	 * @param fileId
	 * @param fileName
	 * @param fileExt
	 * @param creator
	 */
	public FhiFile(String fileId, String fileName, String fileExt) {
		this.fileId = fileId;
		this.fileName = fileName;
		this.fileExt = fileExt;
		this.downloadCount = 0;
		this.createDate = new Date();
		this.isDel = 0;
		this.isTemp = 0;
	}

	public String getFileId() {
		return fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	public String getFileName() {
		if(fileName==null){
			fileName="";
		}
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileExt() {
		return fileExt;
	}

	public void setFileExt(String fileExt) {
		this.fileExt = fileExt;
	}

	public Integer getDownloadCount() {
		return downloadCount;
	}

	public void setDownloadCount(Integer downloadCount) {
		this.downloadCount = downloadCount;
	}

	public String getCreator() {
		return creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Integer getIsDel() {
		return isDel;
	}

	public void setIsDel(Integer isDel) {
		this.isDel = isDel;
	}

	public Integer getIsTemp() {
		return isTemp;
	}

	public void setIsTemp(Integer isTemp) {
		this.isTemp = isTemp;
	}

	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}	
}